name: Update SVG Workflow

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  update_svg:
    runs-on: ubuntu-latest
    env:
      OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run update-svg.py script
        run: python ./update-svg.py
